# Generated by Django 3.2.12 on 2024-10-04 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyBaseModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRegistrationForm',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.mybasemodel')),
                ('Date_of_birth', models.DateTimeField(auto_created=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_no', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=255)),
                ('employee_id', models.IntegerField()),
                ('marital_status', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=100)),
                ('residence_address', models.CharField(max_length=255)),
                ('present_address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=150)),
            ],
            bases=('registration.mybasemodel',),
        ),
    ]
