# Generated by Django 3.2.12 on 2024-10-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeregistrationform',
            name='employee_id',
        ),
    ]
